name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'connect/AssemblyInfo.txt'

jobs:
  ############################################################################################################################
  # Check for path changes and apply path-filtering
  ############################################################################################################################
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      asp: ${{ steps.filter.outputs.asp }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Path filtering
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          asp:
            - 'connect/AssemblyInfo.txt'

  ############################################################################################################################
  # Build and Deploy ITpipesASP
  ############################################################################################################################
  run:
    runs-on: windows-latest
    needs: check-changes
    if: needs.check-changes.outputs.asp == 'true'
    steps:
    - name: Build ITpipesASP
      run: echo "SUCCESS"