name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: echo "Building the project..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'deployEnv'
      url: ${{ steps.deploy.outputs.url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      id: deploy
      run: echo "Deploying the project..."