name: Build and Deploy
on:
  push:
    branches:
      - main
    # paths:
    #   - 'connect/AssemblyInfo.cs'

jobs:
  ############################################################################################################################
  # Check for path changes and apply path-filtering
  ############################################################################################################################
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      connect: ${{ steps.filter.outputs.connect }}
      mobile: ${{ steps.filter.outputs.mobile }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Path filtering
      id: filter
      uses: dorny/paths-filter@v3
      with:
        base: ${{ github.ref }}
        filters: |
          connect:
            - 'connect/AssemblyInfo.cs'
          mobile:
            - 'mobile/AssemblyInfo.cs'

  ############################################################################################################################
  # Build and Deploy ITpipesASP
  ############################################################################################################################
  run:
    runs-on: windows-latest
    needs: check-changes
    if: needs.check-changes.outputs.connect == 'true'
    steps:
    - name: Build ITpipesASP
      run: echo "SUCCESS"