name: Build ITPipes Connect
on:
  push:
    branches: [ "main" ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      path1: ${{ steps.filter.outputs.path1 }}
      path2: ${{ steps.filter.outputs.path2 }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Path filtering
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          path1:
            - 'connect/AssemblyInfo.txt'
          path2:
            - 'mobile/AssemblyInfo.txt'

  job1:
    needs: check-changes
    if: needs.check-changes.outputs.path1 == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Job 1
      run: echo "Job 1 is running because path1 was modified."

  job2:
    needs: check-changes
    if: needs.check-changes.outputs.path2 == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Job 2
      run: echo "Job 2 is running because path2 was modified."