name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: 
    # paths:
    #   - 'connect/AssemblyInfo.cs'

jobs:
  ############################################################################################################################
  # Check the branch name
  ############################################################################################################################
  test_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Write Branch Name with PowerShell
        shell: pwsh
        run: |
          Write-Host "Branch Name: $env:GITHUB_REF_NAME"

