name: Build and Deploy
on:
  push:
    branches:
      - main
    # paths:
    #   - 'connect/AssemblyInfo.cs'

jobs:
  ############################################################################################################################
  # Check for path changes and apply path-filtering
  ############################################################################################################################
  test_branches:
    runs-on: ubuntu-latest
    outputs:
      connect: ${{ steps.filter.outputs.connect }}
      mobile: ${{ steps.filter.outputs.mobile }}
    steps:
    - name: Rename Branch Name in case of '/' or '\' in branch name or if it's a release branch
      shell: pwsh
      run: |
        $branch_name = $env:BRANCH_NAME
        echo $branch_name
